import { AIMessage, HumanMessage, ToolMessage } from "@langchain/core/messages";
import { PAAgentState } from "@/lib/schemas/state";

interface ParsedToolResult {
  success: boolean;
  results: unknown[];
  message?: string;
}

interface FailedToolCall {
  toolName: string;
  args: Record<string, unknown>;
  reason: "empty" | "failed";
}

export async function reflectNode(
  state: PAAgentState,
): Promise<Partial<PAAgentState>> {
  // Messages generated by this reflection cycle only.
  const reflectionMessages: HumanMessage[] = [];
  // 1. Find the latest Reasoner message
  const aiMessages = state.messages.filter(AIMessage.isInstance);
  const latestAIMessage = aiMessages.at(-1);
  if (!latestAIMessage) {
    return {};
  }

  // 2. Get the tool calls requested by the latest Reasoner message
  const currentToolCalls = latestAIMessage.tool_calls ?? [];
  if (currentToolCalls.length === 0) {
    return {};
  }

  // 3. Get IDs of the current tool calls
  const currentToolCallIds = new Set(
    currentToolCalls
      .map((call) => call.id)
      .filter((id): id is string => typeof id === "string" && id.length > 0),
  );

  // 4. Find ONLY ToolMessages belonging to the latest Reasoner tool calls
  const toolMessages = state.messages.filter(
    ToolMessage.isInstance,
  ) as ToolMessage[];

  const currentToolMessages = toolMessages.filter((message) => {
    if (!message.tool_call_id) {
      return false;
    }
    return currentToolCallIds.has(message.tool_call_id);
  });

  if (currentToolMessages.length === 0) {
    return {};
  }

  // 5. Detect empty / failed tool results
  const failedToolCalls: FailedToolCall[] = [];
  for (const toolMessage of currentToolMessages) {
    const parsedResult = parseToolResult(toolMessage);
    if (!parsedResult) {
      continue;
    }

    const isEmpty = parsedResult.success && parsedResult.results.length === 0;
    const isFailed = !parsedResult.success;
    if (!isEmpty && !isFailed) {
      continue;
    }

    const toolCall = currentToolCalls.find(
      (call) => call.id === toolMessage.tool_call_id,
    );

    if (!toolCall) {
      continue;
    }

    failedToolCalls.push({
      toolName: toolCall.name,
      args: toolCall.args as Record<string, unknown>,
      reason: isFailed ? "failed" : "empty",
    });
  }

  // 6. Detect duplicate tool calls
  const duplicateCalls = findDuplicateToolCalls(state);

  // 7. Create ONE reflection message
  {
    /*
  Important:
   - If three imaging searches return empty results,
   - we generate ONE reflection instead of:
  // Reflection
  // Reflection
  // Reflection
  // This is the cleanup we are implementing. */
  }

  const reflectionText = buildReflectionMessage(
    failedToolCalls,
    duplicateCalls,
  );

  if (reflectionText) {
    reflectionMessages.push(new HumanMessage(reflectionText));
  }

  // 8. Return ONLY new reflection messages
  if (reflectionMessages.length === 0) {
    return {};
  }
  return {
    messages: reflectionMessages,
  };
}

// Parse Tool Result
function parseToolResult(message: ToolMessage): ParsedToolResult | null {
  try {
    const content = message.content;
    const text =
      typeof content === "string" ? content : JSON.stringify(content);

    return JSON.parse(text) as ParsedToolResult;
  } catch {
    return null;
  }
}

// Build Reflection Message
function buildReflectionMessage(
  failedToolCalls: FailedToolCall[],
  duplicateCalls: string[],
): string | null {
  if (failedToolCalls.length === 0 && duplicateCalls.length === 0) {
    return null;
  }

  const sections: string[] = [];
  // Empty / failed tool results
  if (failedToolCalls.length > 0) {
    const uniqueFailures = getUniqueFailedToolCalls(failedToolCalls);
    sections.push("The latest tool searches did not return useful evidence.");
    sections.push("");
    for (const failure of uniqueFailures) {
      sections.push(formatFailureGuidance(failure));
    }
  }

  // Duplicate tool calls
  if (duplicateCalls.length > 0) {
    if (sections.length > 0) {
      sections.push("");
    }
    sections.push("WARNING: Duplicate tool call detected.");
    sections.push("");
    sections.push(
      ...duplicateCalls.map(
        (toolName) =>
          `The tool "${toolName}" was called again with identical parameters.`,
      ),
    );
    sections.push("");
    sections.push("Do NOT repeat the same search.");
    sections.push(
      "Use a different search term, another relevant tool, or conclude that the available evidence is insufficient.",
    );
  }

  return sections.join("\n");
}

// Remove duplicate failed tool calls from the same reflection cycle
function getUniqueFailedToolCalls(
  failures: FailedToolCall[],
): FailedToolCall[] {
  const seen = new Set<string>();
  const unique: FailedToolCall[] = [];
  for (const failure of failures) {
    const key = [
      failure.toolName,
      JSON.stringify(failure.args),
      failure.reason,
    ].join("|");

    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    unique.push(failure);
  }
  return unique;
}

// Failure Guidance
function formatFailureGuidance(failure: FailedToolCall): string {
  const searchDescription = formatToolArguments(failure.args);
  const prefix =
    failure.reason === "failed"
      ? `The ${failure.toolName} tool failed.`
      : `The ${failure.toolName} search returned no useful evidence.`;

  switch (failure.toolName) {
    case "search_ehr_notes":
      return [
        prefix,
        searchDescription ? `Search attempted: ${searchDescription}` : "",
        "",
        "Do NOT conclude a policy criterion is unmet solely because this search was empty.",
        "",
        "Try a concise clinical search term instead of a long combined query.",
        "",
        "Suggested EHR search terms:",
        "- physical therapy",
        "- PT",
        "- physiotherapy",
        "- chiropractic",
        "- acupuncture",
        "- home exercise",
        "- therapeutic exercise",
        "- ordered by",
        "- physician order",
        "",
        "Only consider evidence relevant to the diagnosis and body part for this prior authorization.",
        "Evaluate findings only against the policy rules provided in the agent state.",
      ]
        .filter(Boolean)
        .join("\n");

    case "search_pharmacy_records":
      return [
        prefix,
        searchDescription ? `Search attempted: ${searchDescription}` : "",
        "",
        "If clinically relevant, try another medication category:",
        "- NSAID",
        "- Pain Medication",
        "- Anti-inflammatory",
        "- Analgesic",
        "- Muscle Relaxant",
        "",
        "Medication history alone does not prove completion or failure of conservative therapy under the retrieved policy rules.",
      ]
        .filter(Boolean)
        .join("\n");

    case "search_imaging_history":
      return [
        prefix,
        searchDescription ? `Search attempted: ${searchDescription}` : "",
        "",
        "If the retrieved policy requires prior imaging, try:",
        "- Lumbar Spine",
        "- Lumbar X-ray",
        "- Lumbar radiograph",
        "- prior imaging",
        "",
        "Do not treat imaging of an unrelated body part as qualifying evidence.",
        "Only apply imaging findings to criteria present in the retrieved policy rules.",
      ]
        .filter(Boolean)
        .join("\n");
    // case "search_ehr_notes":
    //   return [
    //     prefix,
    //     searchDescription ? `Search attempted: ${searchDescription}` : "",
    //     "",
    //     "Do NOT conclude that conservative therapy was not completed yet.",
    //     "",
    //     "Try a concise clinical search term instead of a long combined query.",
    //     "",
    //     "Suggested EHR search terms:",
    //     "- physical therapy",
    //     "- PT",
    //     "- physiotherapy",
    //     "- chiropractic",
    //     "- acupuncture",
    //     "- home exercise",
    //     "- therapeutic exercise",
    //     "",
    //     "Only consider evidence relevant to the diagnosis and body part associated with the prior authorization request.",
    //   ]
    //     .filter(Boolean)
    //     .join("\n");

    // case "search_pharmacy_records":
    //   return [
    //     prefix,
    //     searchDescription ? `Search attempted: ${searchDescription}` : "",
    //     "",
    //     "If clinically relevant, consider another medication category:",
    //     "- NSAID",
    //     "- Pain Medication",
    //     "- Anti-inflammatory",
    //     "- Analgesic",
    //     "- Muscle Relaxant",
    //     "",
    //     "Medication history alone does not prove completion of 6 weeks of conservative therapy.",
    //   ]
    //     .filter(Boolean)
    //     .join("\n");

    // case "search_imaging_history":
    //   return [
    //     prefix,
    //     searchDescription ? `Search attempted: ${searchDescription}` : "",
    //     "",
    //     "For the lumbar imaging criterion, consider:",
    //     "- Lumbar Spine",
    //     "- Lumbar X-ray",
    //     "- Lumbar Spine X-ray",
    //     "- Lumbar radiograph",
    //     "",
    //     "Do not treat imaging from another body part as qualifying evidence for the lumbar MRI authorization.",
    //   ]
    //     .filter(Boolean)
    //     .join("\n");

    default:
      return [
        prefix,
        searchDescription ? `Search attempted: ${searchDescription}` : "",
        "",
        "Use another relevant search strategy.",
        "Do not repeat a search with identical parameters.",
      ]
        .filter(Boolean)
        .join("\n");
  }
}

// Format Tool Arguments
function formatToolArguments(args: Record<string, unknown>): string {
  const entries = Object.entries(args);

  if (entries.length === 0) {
    return "";
  }
  return entries
    .map(([key, value]) => {
      return `${key}="${String(value)}"`;
    })
    .join(", ");
}

// Duplicate Tool Detection
{
  /*
 Compare the latest tool calls against previous tool calls. A duplicate means:
  - same tool name
  - same arguments
We return unique duplicate tool names so that a single Reflection message is generated. */
}

function findDuplicateToolCalls(state: PAAgentState): string[] {
  const aiMessages = state.messages.filter(AIMessage.isInstance);
  const allToolCalls = aiMessages.flatMap(
    (message) => message.tool_calls ?? [],
  );

  if (allToolCalls.length < 2) {
    return [];
  }
  const duplicates = new Set<string>();
  for (let i = 0; i < allToolCalls.length; i++) {
    for (let j = i + 1; j < allToolCalls.length; j++) {
      const first = allToolCalls[i];
      const second = allToolCalls[j];
      if (
        first.name === second.name &&
        JSON.stringify(first.args) === JSON.stringify(second.args)
      ) {
        duplicates.add(second.name);
      }
    }
  }
  return [...duplicates];
}
